# define default database user, name, and password for PostgreSQL deployment
auth:
  enablePostgresUser: true
  postgresPassword: "StrongPassword"
  username: "app1"
  password: "AppPassword"
  database: "app_db"

# The postgres helm chart deployment will be using PVC postgresql-data-claim
primary:
  persistence:
    mountPath: ./dev
    enabled: true
    existingClaim: "postgresql-data-claim"

ingres:
  enabled: true
  hostname: /*
  path: /